travis:
  secure:
    BINSTAR_TOKEN: oBowZ8bb+c7OGkuRkyRhszZDrVgq3S4YCtmkx6/Cul4XAZdO1lALet1y3x7kFEYY8cSmZ+75r3AEnrx5NuTltYnmL5GpBuvLsMu5Qlvnqbd/m19bUTVL5eR/FdgEFH+gFMCpAJnjX+0mziL81VVoYl+AdH1HUkoKEZWQ40hp3iVxvAFNqwm09VTZ8M/cEyaE2vJCONLUnZZ1CsIPFZtki8BMJQMI+X/l8FeJi+LjTI/zhzLE16UifIE9dji4ymQqE/T9dtaA8dAO28iCLx7OKhnuJmBBrykgJhvl2/OPorn/FqYlcS+cGD9Wwdcu3OeoOOj63xGOhTATKQILiSCXwBAIO1JgcLO+Br+ZcXF3klhgnWqT5ZX6GCU/1Gl5GH71WvOx4fJsljOy/7Cmc4BUbGAAZDWjYCiOKmXDHgeIbcEIOxlv/F0RQYcJo0KZQixU/m/p5A+b2Xtx+9FppZj1Medak7+1qRwWMy6RPX4puFMLMQWx4VauR/VT6teWRuM4QhSRUVG/41IXM/9WDcC8+G8V/FMrCK+as9Om8QFqrEpyow1/7NGW6GuuV+jg7MJ5Ta7/BOgge4UXxkdyStgEsOUnvA3LPXLkTtiEIWtt55yY/lHVS9HEfVPnEfceEEJZ+AgGjsqXQwNhu3cJpAg7M5SUUN99Mkl1PuXLLaeG42w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
