travis:
  secure:
    BINSTAR_TOKEN: u4EDkRT0qCZ7KSC7dcMpWRwNGc/btQEdRZ+pq1Ngh6zPtm2j6aKXjvCeUeSsbLlT2VLsVoTniWTvrBVHL8/e1s7TBkHZDEQCmymbi4vlc8ooPMFy37npIgZHTSJOjDsU6jZGKO7rTz4ItQlW4ipZqzVdBTZgBsyK/cqKvlsOijJY9PheI14aykEsSrKYrIG3gMOZJ35w3YmmFAFBtlfoO0Zpc8Jp9RgWbgcrd3f1AcQALKL46PEPioF4Sn5JAyioxZei4ogPnh/y8Jv+rkn2oAT+/oWtLIVONSJjSFq1IVw/A4wqG3j81Cq4YTrQeteSFmgbDapZms0zl1QNR+8aBg0T5PestXajgFwiuxj0yav4BKP7ey5CX96uzdavJKdfzCYLoKFXQyqtz2lNiBue9iRtfXMatiRtKfgiDWfYp7QvWe56Rw0ePeyTMsMsrvyxJWOZ3LUdit0D9+mLhOdwzXyFqpJNrwXdljCBngHFJlxti84UtPXveQTF5lrFnKP+MrudWK6sb+mWZOAczGFyxSau/2Nci50u9Vg5CUYYTOAAPzxW3827f5TfoXOxh9svtccs85m4Lbdu8JhBlJnTEJMS4RuKDQfKQLcAzs1FRr8tYkulzt586PxUuqfpftAZH1seeVQudoCLvM4ybSEUNAbftfpOGlE9RD/+MzmKRPs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
