travis:
  secure:
    BINSTAR_TOKEN: xIKMFLcyEs0ARHtti3ez6QTa1lD0/8OdE1OJtgsnq+HO05qmRQz2n39Lrg3ya4xyYLtCT2oijR1xUTS6llekXu2QZPQfQp8i0/WaRvh2QX6rNL/Zo93TfZukfj/ZA8YooJ8Vloqmi/iOZ6lbzTyIGZ/8GcZ0ShWW7h6+68rgCRPzRzIsWk43unQDBcrOoyXXuOyLteNd0DB/SJEPfov+AMix2+eW2XLA5xEVKAyvDumxlnRUzOzuY9bRSM3arnKqRiUs+A8EtzNnSeu+dqqNEGB8dX5+kv2WZp/gnnh4AbYwEVhqu0GkqDCjsVyLDMGy7Je5ZpYea645S5PcLvw9MJogQGYJBhhkMtC/rNORR8r9nRDEkQj/RiVaEEIbVHtqF8YQ3YMm5cAoTXXQTT57XrvIJMGx4s4zainnmsAjR85QZdVgkA40rXF8I3vK70jc7PEEEcNkYgDSNjTbn7bjOrUnIu3Cntarf4nk87TdlLxQlKH++zr6HkvDXMTa6nUFM3CHfcbTPA30MzBz1HxQR4vLOGJ/09jx2L+I7Ft44BASf7A5GLdE2R3bYtLTpDGfSerHldEbJ5ItVs92lq1NURzUiLayzrk2ubZAhITTvycvCXaOwXKqXFGDvnfTPEvw0SP0ubi/BUkeGlL/+pcHIrCNEPy6EvoJeBXFZd2lu98=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
